server:
  port: 2333
spring:
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀

    cache: false  #是否使用缓存
    mode: LEGACYHTML5  #不太严格的HTML5语法模式
    suffix: .html  #后缀名


